# Generated by Django 5.2 on 2025-04-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField(default='Текст обо мне на русском...', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(default='About me text in English...', verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': "Секция 'Обо мне'",
                'verbose_name_plural': "Секция 'Обо мне'",
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@eduardbosak.ru', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+7 (995) 079-97-77', max_length=30, verbose_name='Телефон')),
                ('location_ru', models.CharField(default='Москва, Россия (м. Красногвардейская)', max_length=150, verbose_name='Местоположение (RU)')),
                ('location_en', models.CharField(default='Moscow, Russia (m. Krasnogvardeyskaya)', max_length=150, verbose_name='Местоположение (EN)')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_ru', models.CharField(max_length=250, verbose_name='Степень/Название (RU)')),
                ('degree_en', models.CharField(max_length=250, verbose_name='Степень/Название (EN)')),
                ('institution_ru', models.CharField(max_length=300, verbose_name='Учебное заведение (RU)')),
                ('institution_en', models.CharField(max_length=300, verbose_name='Учебное заведение (EN)')),
                ('year_ru', models.CharField(max_length=50, verbose_name='Год окончания (RU)')),
                ('year_en', models.CharField(max_length=50, verbose_name='Год окончания (EN)')),
                ('is_course_section', models.BooleanField(default=False, help_text='Отметьте, если это заголовок для списка курсов', verbose_name='Это секция доп. курсов?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Образование / Квалификация',
                'verbose_name_plural': 'Образование и Квалификации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Должность (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Должность (EN)')),
                ('company_ru', models.CharField(max_length=200, verbose_name='Компания (RU)')),
                ('company_en', models.CharField(max_length=200, verbose_name='Компания (EN)')),
                ('period_ru', models.CharField(help_text='Например: Фев 2022 – Июн 2024 (2 г. 5 мес.)', max_length=100, verbose_name='Период (RU)')),
                ('period_en', models.CharField(help_text='Example: Feb 2022 – Jun 2024 (2 yrs 5 mos)', max_length=100, verbose_name='Период (EN)')),
                ('location_ru', models.CharField(blank=True, max_length=100, verbose_name='Местоположение (RU)')),
                ('location_en', models.CharField(blank=True, max_length=100, verbose_name='Местоположение (EN)')),
                ('responsibilities_ru', models.TextField(help_text='Каждый пункт с новой строки, можно использовать markdown или html', verbose_name='Обязанности (RU)')),
                ('responsibilities_en', models.TextField(help_text='Each item on a new line, markdown or html can be used', verbose_name='Обязанности (EN)')),
                ('achievements_ru', models.TextField(blank=True, help_text='Каждый пункт с новой строки', verbose_name='Достижения (RU)')),
                ('achievements_en', models.TextField(blank=True, help_text='Each item on a new line', verbose_name='Достижения (EN)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше позиция в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Привет! Я Эдуард Босак', max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(default="Hi! I'm Eduard Bosak", max_length=200, verbose_name='Заголовок (EN)')),
                ('subtitle_ru', models.CharField(default='Менеджер проектов и клиентского сервиса', max_length=300, verbose_name='Подзаголовок (RU)')),
                ('subtitle_en', models.CharField(default='Project and Customer Experience Manager', max_length=300, verbose_name='Подзаголовок (EN)')),
                ('small_subtitle_ru', models.CharField(blank=True, default='Открыт к переезду в Санкт-Петербург и командировкам.', max_length=300, verbose_name='Малый подзаголовок (RU)')),
                ('small_subtitle_en', models.CharField(blank=True, default='Open to relocation to St. Petersburg and business trips.', max_length=300, verbose_name='Малый подзаголовок (EN)')),
            ],
            options={
                'verbose_name': 'Секция Hero',
                'verbose_name_plural': 'Секция Hero',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название проекта (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название проекта (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название категории (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название категории (EN)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше категория', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория навыков',
                'verbose_name_plural': 'Категории навыков',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название курса (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название курса (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('education_entry', models.ForeignKey(limit_choices_to={'is_course_section': True}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.education', verbose_name='Раздел образования')),
            ],
            options={
                'verbose_name': 'Дополнительный курс',
                'verbose_name_plural': 'Дополнительные курсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название навыка (RU)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Название навыка (EN)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше навык внутри категории', verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='content.skillcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'order'],
            },
        ),
    ]
