# Generated by Django 5.2 on 2025-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_about_ru', models.CharField(default='Обо мне', max_length=50, verbose_name='Меню: Обо мне (RU)')),
                ('nav_about_en', models.CharField(default='About', max_length=50, verbose_name='Меню: Обо мне (EN)')),
                ('nav_skills_ru', models.CharField(default='Навыки', max_length=50, verbose_name='Меню: Навыки (RU)')),
                ('nav_skills_en', models.CharField(default='Skills', max_length=50, verbose_name='Меню: Навыки (EN)')),
                ('nav_experience_ru', models.CharField(default='Опыт', max_length=50, verbose_name='Меню: Опыт (RU)')),
                ('nav_experience_en', models.CharField(default='Experience', max_length=50, verbose_name='Меню: Опыт (EN)')),
                ('nav_education_ru', models.CharField(default='Образование', max_length=50, verbose_name='Меню: Образование (RU)')),
                ('nav_education_en', models.CharField(default='Education', max_length=50, verbose_name='Меню: Образование (EN)')),
                ('nav_projects_ru', models.CharField(default='Проекты', max_length=50, verbose_name='Меню: Проекты (RU)')),
                ('nav_projects_en', models.CharField(default='Projects', max_length=50, verbose_name='Меню: Проекты (EN)')),
                ('nav_contact_ru', models.CharField(default='Контакты', max_length=50, verbose_name='Меню: Контакты (RU)')),
                ('nav_contact_en', models.CharField(default='Contact', max_length=50, verbose_name='Меню: Контакты (EN)')),
                ('cta_projects_ru', models.CharField(default='Мои проекты', max_length=50, verbose_name='Кнопка: Мои проекты (RU)')),
                ('cta_projects_en', models.CharField(default='My Projects', max_length=50, verbose_name='Кнопка: Мои проекты (EN)')),
                ('cta_contact_ru', models.CharField(default='Связаться со мной', max_length=50, verbose_name='Кнопка: Связаться (RU)')),
                ('cta_contact_en', models.CharField(default='Contact Me', max_length=50, verbose_name='Кнопка: Связаться (EN)')),
                ('section_about_ru', models.CharField(default='Обо мне', max_length=50, verbose_name='Заголовок: Обо мне (RU)')),
                ('section_about_en', models.CharField(default='About Me', max_length=50, verbose_name='Заголовок: Обо мне (EN)')),
                ('section_skills_ru', models.CharField(default='Ключевые навыки', max_length=50, verbose_name='Заголовок: Навыки (RU)')),
                ('section_skills_en', models.CharField(default='Key Skills', max_length=50, verbose_name='Заголовок: Навыки (EN)')),
                ('section_experience_ru', models.CharField(default='Опыт работы', max_length=50, verbose_name='Заголовок: Опыт (RU)')),
                ('section_experience_en', models.CharField(default='Work Experience', max_length=50, verbose_name='Заголовок: Опыт (EN)')),
                ('section_education_ru', models.CharField(default='Образование', max_length=50, verbose_name='Заголовок: Образование (RU)')),
                ('section_education_en', models.CharField(default='Education', max_length=50, verbose_name='Заголовок: Образование (EN)')),
                ('section_projects_ru', models.CharField(default='Проекты', max_length=50, verbose_name='Заголовок: Проекты (RU)')),
                ('section_projects_en', models.CharField(default='Projects', max_length=50, verbose_name='Заголовок: Проекты (EN)')),
                ('section_contact_ru', models.CharField(default='Контакты', max_length=50, verbose_name='Заголовок: Контакты (RU)')),
                ('section_contact_en', models.CharField(default='Contact', max_length=50, verbose_name='Заголовок: Контакты (EN)')),
                ('label_responsibilities_ru', models.CharField(default='Обязанности:', max_length=50, verbose_name='Метка: Обязанности (RU)')),
                ('label_responsibilities_en', models.CharField(default='Responsibilities:', max_length=50, verbose_name='Метка: Обязанности (EN)')),
                ('label_achievements_ru', models.CharField(default='Достижения:', max_length=50, verbose_name='Метка: Достижения (RU)')),
                ('label_achievements_en', models.CharField(default='Achievements:', max_length=50, verbose_name='Метка: Достижения (EN)')),
                ('label_graduation_year_ru', models.CharField(default='Год окончания:', max_length=50, verbose_name='Метка: Год окончания (RU)')),
                ('label_graduation_year_en', models.CharField(default='Graduation Year:', max_length=50, verbose_name='Метка: Год окончания (EN)')),
                ('label_preferred_contact_ru', models.CharField(default='(Предпочтительный способ связи)', max_length=100, verbose_name='Метка: Предпочтительный способ связи (RU)')),
                ('label_preferred_contact_en', models.CharField(default='(Preferred contact method)', max_length=100, verbose_name='Метка: Предпочтительный способ связи (EN)')),
                ('copyright_text_ru', models.CharField(default='Все права защищены.', max_length=100, verbose_name='Копирайт (RU)')),
                ('copyright_text_en', models.CharField(default='All rights reserved.', max_length=100, verbose_name='Копирайт (EN)')),
            ],
            options={
                'verbose_name': 'Тексты интерфейса',
                'verbose_name_plural': 'Тексты интерфейса',
            },
        ),
    ]
