# Generated by Django 5.2 on 2025-04-26 16:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('degree_ru', models.CharField(max_length=250, verbose_name='Степень/Название (RU)')),
                ('degree_en', models.CharField(max_length=250, verbose_name='Степень/Название (EN)')),
                ('institution_ru', models.CharField(max_length=300, verbose_name='Учебное заведение (RU)')),
                ('institution_en', models.CharField(max_length=300, verbose_name='Учебное заведение (EN)')),
                ('year_ru', models.CharField(max_length=50, verbose_name='Год окончания (RU)')),
                ('year_en', models.CharField(max_length=50, verbose_name='Год окончания (EN)')),
                ('is_course_section', models.BooleanField(default=False, verbose_name='Это секция доп. курсов?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Образование / Квалификация',
                'verbose_name_plural': 'Образование и Квалификации',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title_ru', models.CharField(default='Привет! Я Эдуард Босак', max_length=200, verbose_name='Заголовок (RU)')),
                ('hero_title_en', models.CharField(default="Hi! I'm Eduard Bosak", max_length=200, verbose_name='Заголовок (EN)')),
                ('hero_subtitle_ru', models.CharField(default='Менеджер проектов и клиентского сервиса', max_length=300, verbose_name='Подзаголовок (RU)')),
                ('hero_subtitle_en', models.CharField(default='Project and Customer Experience Manager', max_length=300, verbose_name='Подзаголовок (EN)')),
                ('small_subtitle_ru', models.CharField(blank=True, default='Открыт к переезду в Санкт-Петербург и командировкам.', max_length=300, verbose_name='Малый подзаголовок (RU)')),
                ('small_subtitle_en', models.CharField(blank=True, default='Open to relocation to St. Petersburg and business trips.', max_length=300, verbose_name='Малый подзаголовок (EN)')),
                ('about_me_ru', wagtail.fields.RichTextField(blank=True, verbose_name='О себе (RU)')),
                ('about_me_en', wagtail.fields.RichTextField(blank=True, verbose_name='О себе (EN)')),
                ('ui_texts_title', models.CharField(default='Тексты интерфейса', help_text='Административное обозначение', max_length=200, verbose_name='Заголовок группы UI текстов')),
                ('cta_projects_ru', models.CharField(default='Мои проекты', max_length=50, verbose_name='Кнопка: Мои проекты (RU)')),
                ('cta_projects_en', models.CharField(default='My Projects', max_length=50, verbose_name='Кнопка: Мои проекты (EN)')),
                ('cta_contact_ru', models.CharField(default='Связаться со мной', max_length=50, verbose_name='Кнопка: Связаться (RU)')),
                ('cta_contact_en', models.CharField(default='Contact Me', max_length=50, verbose_name='Кнопка: Связаться (EN)')),
                ('email', models.EmailField(default='info@eduardbosak.ru', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+7 (995) 079-97-77', max_length=30, verbose_name='Телефон')),
                ('location_ru', models.CharField(default='Москва, Россия (м. Красногвардейская)', max_length=150, verbose_name='Местоположение (RU)')),
                ('location_en', models.CharField(default='Moscow, Russia (m. Krasnogvardeyskaya)', max_length=150, verbose_name='Местоположение (EN)')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_about_ru', models.CharField(default='Обо мне', max_length=50, verbose_name='Меню: Обо мне (RU)')),
                ('nav_about_en', models.CharField(default='About', max_length=50, verbose_name='Меню: Обо мне (EN)')),
                ('nav_skills_ru', models.CharField(default='Навыки', max_length=50, verbose_name='Меню: Навыки (RU)')),
                ('nav_skills_en', models.CharField(default='Skills', max_length=50, verbose_name='Меню: Навыки (EN)')),
                ('nav_experience_ru', models.CharField(default='Опыт', max_length=50, verbose_name='Меню: Опыт (RU)')),
                ('nav_experience_en', models.CharField(default='Experience', max_length=50, verbose_name='Меню: Опыт (EN)')),
                ('nav_education_ru', models.CharField(default='Образование', max_length=50, verbose_name='Меню: Образование (RU)')),
                ('nav_education_en', models.CharField(default='Education', max_length=50, verbose_name='Меню: Образование (EN)')),
                ('nav_projects_ru', models.CharField(default='Проекты', max_length=50, verbose_name='Меню: Проекты (RU)')),
                ('nav_projects_en', models.CharField(default='Projects', max_length=50, verbose_name='Меню: Проекты (EN)')),
                ('nav_contact_ru', models.CharField(default='Контакты', max_length=50, verbose_name='Меню: Контакты (RU)')),
                ('nav_contact_en', models.CharField(default='Contact', max_length=50, verbose_name='Меню: Контакты (EN)')),
                ('section_about_ru', models.CharField(default='Обо мне', max_length=50, verbose_name='Заголовок: Обо мне (RU)')),
                ('section_about_en', models.CharField(default='About Me', max_length=50, verbose_name='Заголовок: Обо мне (EN)')),
                ('section_skills_ru', models.CharField(default='Ключевые навыки', max_length=50, verbose_name='Заголовок: Навыки (RU)')),
                ('section_skills_en', models.CharField(default='Key Skills', max_length=50, verbose_name='Заголовок: Навыки (EN)')),
                ('section_experience_ru', models.CharField(default='Опыт работы', max_length=50, verbose_name='Заголовок: Опыт (RU)')),
                ('section_experience_en', models.CharField(default='Work Experience', max_length=50, verbose_name='Заголовок: Опыт (EN)')),
                ('section_education_ru', models.CharField(default='Образование', max_length=50, verbose_name='Заголовок: Образование (RU)')),
                ('section_education_en', models.CharField(default='Education', max_length=50, verbose_name='Заголовок: Образование (EN)')),
                ('section_projects_ru', models.CharField(default='Проекты', max_length=50, verbose_name='Заголовок: Проекты (RU)')),
                ('section_projects_en', models.CharField(default='Projects', max_length=50, verbose_name='Заголовок: Проекты (EN)')),
                ('section_contact_ru', models.CharField(default='Контакты', max_length=50, verbose_name='Заголовок: Контакты (RU)')),
                ('section_contact_en', models.CharField(default='Contact', max_length=50, verbose_name='Заголовок: Контакты (EN)')),
                ('label_responsibilities_ru', models.CharField(default='Обязанности:', max_length=50, verbose_name='Метка: Обязанности (RU)')),
                ('label_responsibilities_en', models.CharField(default='Responsibilities:', max_length=50, verbose_name='Метка: Обязанности (EN)')),
                ('label_achievements_ru', models.CharField(default='Достижения:', max_length=50, verbose_name='Метка: Достижения (RU)')),
                ('label_achievements_en', models.CharField(default='Achievements:', max_length=50, verbose_name='Метка: Достижения (EN)')),
                ('label_graduation_year_ru', models.CharField(default='Год окончания:', max_length=50, verbose_name='Метка: Год окончания (RU)')),
                ('label_graduation_year_en', models.CharField(default='Graduation Year:', max_length=50, verbose_name='Метка: Год окончания (EN)')),
                ('label_preferred_contact_ru', models.CharField(default='(Предпочтительный способ связи)', max_length=100, verbose_name='Метка: Предпочтительный способ связи (RU)')),
                ('label_preferred_contact_en', models.CharField(default='(Preferred contact method)', max_length=100, verbose_name='Метка: Предпочтительный способ связи (EN)')),
                ('copyright_text_ru', models.CharField(default='Все права защищены.', max_length=100, verbose_name='Копирайт (RU)')),
                ('copyright_text_en', models.CharField(default='All rights reserved.', max_length=100, verbose_name='Копирайт (EN)')),
            ],
            options={
                'verbose_name': 'Настройки интерфейса',
                'verbose_name_plural': 'Настройки интерфейса',
            },
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название курса (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название курса (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('education', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portfolio_cms.educationrelation')),
            ],
            options={
                'verbose_name': 'Дополнительный курс',
                'verbose_name_plural': 'Дополнительные курсы',
            },
        ),
        migrations.CreateModel(
            name='ExperienceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_ru', models.CharField(max_length=200, verbose_name='Должность (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Должность (EN)')),
                ('company_ru', models.CharField(max_length=200, verbose_name='Компания (RU)')),
                ('company_en', models.CharField(max_length=200, verbose_name='Компания (EN)')),
                ('period_ru', models.CharField(max_length=100, verbose_name='Период (RU)')),
                ('period_en', models.CharField(max_length=100, verbose_name='Период (EN)')),
                ('location_ru', models.CharField(blank=True, max_length=100, verbose_name='Местоположение (RU)')),
                ('location_en', models.CharField(blank=True, max_length=100, verbose_name='Местоположение (EN)')),
                ('responsibilities_ru', wagtail.fields.RichTextField(verbose_name='Обязанности (RU)')),
                ('responsibilities_en', wagtail.fields.RichTextField(verbose_name='Обязанности (EN)')),
                ('achievements_ru', wagtail.fields.RichTextField(blank=True, verbose_name='Достижения (RU)')),
                ('achievements_en', wagtail.fields.RichTextField(blank=True, verbose_name='Достижения (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio_cms.portfoliopage')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.AddField(
            model_name='educationrelation',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio_cms.portfoliopage'),
        ),
        migrations.CreateModel(
            name='ProjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название проекта (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название проекта (EN)')),
                ('description_ru', wagtail.fields.RichTextField(verbose_name='Описание (RU)')),
                ('description_en', wagtail.fields.RichTextField(verbose_name='Описание (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio_cms.portfoliopage')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SkillCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название категории (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название категории (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='portfolio_cms.portfoliopage')),
            ],
            options={
                'verbose_name': 'Категория навыков',
                'verbose_name_plural': 'Категории навыков',
            },
        ),
        migrations.CreateModel(
            name='SkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название навыка (RU)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Название навыка (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_cms.skillcategoryrelation')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
