# Generated by Django 5.2 on 2025-04-26 18:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrelation',
            name='degree_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Степень/Название (EN)'),
        ),
        migrations.AlterField(
            model_name='educationrelation',
            name='institution_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Учебное заведение (EN)'),
        ),
        migrations.AlterField(
            model_name='educationrelation',
            name='year_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Год окончания (EN)'),
        ),
        migrations.AlterField(
            model_name='experiencerelation',
            name='company_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Компания (EN)'),
        ),
        migrations.AlterField(
            model_name='experiencerelation',
            name='period_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Период (EN)'),
        ),
        migrations.AlterField(
            model_name='experiencerelation',
            name='responsibilities_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Обязанности (EN)'),
        ),
        migrations.AlterField(
            model_name='experiencerelation',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность (EN)'),
        ),
        migrations.AlterField(
            model_name='projectrelation',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='projectrelation',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название проекта (EN)'),
        ),
    ]
