# Generated by Django 5.2 on 2025-04-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cms', '0002_alter_educationrelation_degree_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserelation',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название курса (EN)'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='location_en',
            field=models.CharField(default='Moscow, Russia (m. Красногвардейская)', max_length=150, verbose_name='Местоположение (EN)'),
        ),
        migrations.AlterField(
            model_name='skillcategoryrelation',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название категории (EN)'),
        ),
        migrations.AlterField(
            model_name='skillrelation',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название навыка (EN)'),
        ),
    ]
